---

# Keep the default Vagrant SSH key. It's publicly available and thus
# "insecure", but these VMs aren't for production use and having a well-known
# key allows for easy automation and documentation.
ssh:
  insert_key: false

vms:

  # NOTE: All `box:` declarations in this example point to vagrantcloud.com
  # and require Vagrant 1.5.0 or newer to function.
#  - name: pe-201611-master
#    debug-kit: true
#    box: puppetlabs/centos-7.2-64-nocm
#    roles:
#      - pe-forward-console
#      - pe-memory-tuning2
#      - el-stop-firewall
#      - el-fix-path
#      - 4gb-memory
#      - base

#  - name: artifactory1
#    debug-kit: true
#    box: puppetlabs/centos-7.2-64-nocm
#    roles:
#      - pe-201611-agent
#      - el-stop-firewall
#      - el-fix-path
#      - artifactory-role
#      - 1gb-memory
#      - base

  - name: centos7s0
    debug-kit: true
    box: puppetlabs/centos-7.2-64-nocm
    roles:
      #- pe-201611-agent
      - el-stop-firewall
      - el-fix-path
      - dia-role
      - gui-4gb
      - base
